[program:octane]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan octane:start  --host=0.0.0.0 --port=8000 --admin-port=2019
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/logs/octane.log
stopwaitsecs=3600

[program:worker]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=root
numprocs=2
redirect_stderr=true
stdout_logfile=/app/storage/logs/octane.log
stopwaitsecs=3600
