[program:octane]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000 --admin-port=2019 --max-requests=1000
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/app/storage/logs/octane.log
stopwaitsecs=3600

[program:worker]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/app/storage/logs/worker.log
stopwaitsecs=3600

[program:socket-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan reverb:start --port=8080 --host=0.0.0.0
autostart=true
autorestart=true
user=www-data
# FIX 6: MUST be 1 process for WebSockets binding to a single port
numprocs=1
redirect_stderr=true
stdout_logfile=/app/storage/logs/reverb.log
stopwaitsecs=3600

[program:scheduler]
process_name=%(program_name)s_%(process_num)02d
command=/bin/sh -c "while [ true ]; do (php /app/artisan schedule:run --verbose --no-interaction &); sleep 60; done"
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/app/storage/logs/scheduler.log
stopwaitsecs=3600
