[program:octane]
process_name=%(program_name)s_%(process_num)02d
command=/bin/sh -c "rm -f /app/storage/logs/octane-server-state.json && php /app/artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000 --admin-port=2019 --max-requests=1000 --no-interaction"
directory=/app
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=3600

[program:worker]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --no-interaction
directory=/app
autostart=true
autorestart=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=3600

[program:socket-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan reverb:start --port=8080 --host=0.0.0.0 --no-interaction
directory=/app
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=3600

[program:scheduler]
process_name=%(program_name)s_%(process_num)02d
# For production, schedule:work is a convenient way to run the scheduler in a long-running process
# Ensuring --no-interaction is critical for unattended environments
command=php /app/artisan schedule:work --no-interaction
directory=/app
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=3600

